name: Sync Upstream (Hourly)

on:
  schedule:
    - cron: '0 * * * *' # Spouští se každou hodinu
  workflow_dispatch:     # Ruční spuštění

jobs:
  sync_latest_from_upstream:
    name: Sync Latest Commits from Upstream
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync upstream changes
        uses: pujiyung/actions-upstream-sync@v2.5.1
        with:
          upstream_sync_repo: 'VaraiTamas/VTomRadio' # ZDE DOPLŇ SPRÁVNÉHO AUTORA (např. 'tom/VTomRadio')
          upstream_sync_branch: 'main'                  # Případně 'master' podle originálu
          target_sync_branch: 'main'                    # Tvoje větev
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
